# Generated by Django 4.2.5 on 2023-09-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('calories', models.IntegerField()),
                ('bilky', models.IntegerField()),
                ('zhury', models.IntegerField()),
                ('vuglevody', models.IntegerField()),
            ],
        ),
    ]
